### ISSUE TITLE
东风风行获取不到微信名字阿

### ISSUE THREAD

**Issue by kkkkxl** [SkyNightovo/js#5]
![image](https://user-images.githubusercontent.com/37541028/198932225-518fe515-73da-4705-b876-1cec3bedcb9d.png)

**Comment by SkyNightovo** [comment]
微信授权登录自己的用户名和手机号，抓https://weixin.dflzm.com.cn/tg-car-api/mini/carMasterVip/findByOpenId，里的body，放进去

**Comment by kkkkxl** [comment]
> 微信授权登录自己的用户名和手机号，抓[https://weixin.dflzm.com.cn/tg-car-api/mini/carMasterVip/findByOpenId，里的body，放进去](https://weixin.dflzm.com.cn/tg-car-api/mini/carMasterVip/findByOpenId%EF%BC%8C%E9%87%8C%E7%9A%84body%EF%BC%8C%E6%94%BE%E8%BF%9B%E5%8E%BB)

不行 抓的就是这个请求的body

**Comment by kkkkxl** [comment]
> 微信授权登录自己的用户名和手机号，抓[https://weixin.dflzm.com.cn/tg-car-api/mini/carMasterVip/findByOpenId，里的body，放进去](https://weixin.dflzm.com.cn/tg-car-api/mini/carMasterVip/findByOpenId%EF%BC%8C%E9%87%8C%E7%9A%84body%EF%BC%8C%E6%94%BE%E8%BF%9B%E5%8E%BB)

![image](https://user-images.githubusercontent.com/37541028/198954482-e39bdb73-025a-45be-b5ca-f413e069fe20.png)
fake_f7f56fac8f824f2fa235883dfddde373
你可以试一下

**Comment by SkyNightovo** [comment]
ck不长这样

**Comment by SkyNightovo** [comment]
全局搜openid吧

**Comment by kkkkxl** [comment]
> 全局搜openid吧

![image](https://user-images.githubusercontent.com/37541028/198955021-bd90cff8-8521-45e4-9846-443cad30ce8c.png)
不是这样吗

**Comment by SkyNightovo** [comment]
不长这样，类似于 oKeuHXXXXXXXXXXXPg，以 oKeu开头，苹果不知道，我安卓

**Comment by kkkkxl** [comment]
> 不长这样，类似于 oKeuHXXXXXXXXXXXPg，以 oKeu开头，苹果不知道，我安卓

我是苹果的, 那估计玩不了 这个接口的请求body就这样 跟你不一样
